#CREATE DATABASE human_friends;

USE human_friends;

DROP TABLE IF EXISTS cats;
DROP TABLE IF EXISTS dogs;
DROP TABLE IF EXISTS hamsters;
DROP TABLE IF EXISTS camels;
DROP TABLE IF EXISTS horses;
DROP TABLE IF EXISTS donkeys;
DROP TABLE IF EXISTS pet_commands;
DROP TABLE IF EXISTS pack_animal_commands;
DROP TABLE IF EXISTS commands;
DROP TABLE IF EXISTS pack_animals;
DROP TABLE IF EXISTS pets;



CREATE TABLE pets (
    id INT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    birth_date DATE NOT NULL,
    gender VARCHAR(6) NOT NULL
);

CREATE TABLE pack_animals (
    id INT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
    name VARCHAR(45) NOT NULL,
    birth_date DATE NOT NULL,
    gender VARCHAR(6) NOT NULL
);

CREATE TABLE cats (
    id INT UNSIGNED UNIQUE NOT NULL PRIMARY KEY,
    CONSTRAINT fk_cat FOREIGN KEY(id) REFERENCES pets(id)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
    
CREATE TABLE dogs (
	id INT UNSIGNED UNIQUE NOT NULL PRIMARY KEY,
    CONSTRAINT fk_dog FOREIGN KEY(id) REFERENCES pets(id)
    ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE hamsters (
	id INT UNSIGNED UNIQUE NOT NULL PRIMARY KEY,
    CONSTRAINT fk_hamster FOREIGN KEY(id) REFERENCES pets(id)
    ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE camels (
	id INT UNSIGNED UNIQUE NOT NULL PRIMARY KEY,
    CONSTRAINT fk_camel FOREIGN KEY(id) REFERENCES pack_animals(id)
    ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE horses (
	id INT UNSIGNED UNIQUE NOT NULL PRIMARY KEY,
    CONSTRAINT fk_horses FOREIGN KEY(id) REFERENCES pack_animals(id)
    ON DELETE CASCADE
	ON UPDATE CASCADE
);

CREATE TABLE donkeys (
	id INT UNSIGNED UNIQUE NOT NULL PRIMARY KEY,
    CONSTRAINT fk_donkey FOREIGN KEY(id) REFERENCES pack_animals(id)
    ON DELETE CASCADE
	ON UPDATE CASCADE
);


CREATE TABLE commands (
	id INT UNSIGNED AUTO_INCREMENT UNIQUE NOT NULL PRIMARY KEY,
    name VARCHAR(45) UNIQUE NOT NULL
);

CREATE TABLE pet_commands (
    id_pet INT UNSIGNED NOT NULL,
	id_command INT UNSIGNED NOT NULL,
    PRIMARY KEY(id_pet, id_command),
	FOREIGN KEY(id_pet) REFERENCES pets(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    FOREIGN KEY(id_command) REFERENCES commands(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);

CREATE TABLE pack_animal_commands (
    id_pack_animal INT UNSIGNED NOT NULL,
	id_command INT UNSIGNED NOT NULL,
    PRIMARY KEY(id_pack_animal, id_command),
	FOREIGN KEY(id_pack_animal) REFERENCES pack_animals(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE,
    FOREIGN KEY(id_command) REFERENCES commands(id)
		ON DELETE CASCADE
		ON UPDATE CASCADE
);
