services:
  db:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/my_secret_password
    ports:
      - "6033:3306"
    volumes:
      - ./create_db.sql:/docker-entrypoint-initdb.d/1-create_db.sql
      - ./insert_values.sql:/docker-entrypoint-initdb.d/2-insert_values.sql
    restart: always
    secrets:
      - my_secret_password

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: pma
    restart: always
    environment:
      PMA_HOST: db
    ports:
      - 8081:80
    depends_on:
      - db

  app:
    build: .
    container_name: app
    restart: always
    stdin_open: true
    tty: true
    environment:
      MYSQL_USER: root
      MYSQL_PASSWORD: Password
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    depends_on:
      - db

secrets:
  my_secret_password:
    file: ./my_secret_password.txt
